"""Add stripe_payment_intent_id to orders

Revision ID: 171930b5bdb5
Revises: 1a025198bd64
Create Date: 2025-04-13 17:11:32.513995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171930b5bdb5'
down_revision = '1a025198bd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False))
        batch_op.create_unique_constraint('uq_stripe_payment_intent_id', ['stripe_payment_intent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stripe_payment_intent_id', type_='unique')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
