"""Add admin and blocked status to users

Revision ID: 365344704f24
Revises: 
Create Date: 2025-03-06 19:30:34.291197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365344704f24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
